
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
      - name: gateway
        image: gateway:0.1.0
        ports: [{ containerPort: 8000 }]
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef: { name: app-secrets }
        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector: { app: gateway }
  ports:
  - name: http
    port: 80
    targetPort: 8000
